language: java
install: true
jdk: openjdk7
env:
  - COREOS_CHANNEL=Stable
  - COREOS_CHANNEL=Beta
  - COREOS_CHANNEL=Alpha

script: travis_wait 60 ./import_coreos.sh

notifications:
  email:
    on_success: change
    on_failure: change
