language: java
install: true
jdk: openjdk7
env:
  matrix:
  - COREOS_CHANNEL=Stable
  - COREOS_CHANNEL=Beta
  - COREOS_CHANNEL=Alpha
  global:
  - secure: aUTndP8EqrDRSQAICFHRJyigKvUCCQ/dFZIgYvUhK6DpnMsNZem/5J/e4Gt+B+F/cYi23xUuH9iQrrhr3RJy/3YXGTWbhFgFApVKtk5eKz24KJAKPrbFvPpiVSf+Vgfh0LMUXp2IlwqFcexW7K3RxS0WxiQh2Fmo6URkRzxnz44=
  - secure: MFTLvUWalBr793PpDjB6OPIX8/EhmxODcLotns8Mx1A5lAt733wJe5+z8uybk/DGKUbpmWh0EW4Dcx06c/MkPWW1hnf/YQex1XmQoKd19dfUirJ8IV8LoF47nuU57OUq3IFCuMpXEZosYGNfh3kQHwZsiyKpi/DhU+AIlUXqXEk=
  - secure: S+1GvO9wlvnNur0/ZxtIKq9q3uhP/UdTKQGX22YU1wRrNKfYkb22TJDZtmDCBnO79GQEN+zZct54BCVx3p4CxSReF4RPeYOFsW42kP1c6vAeEa8bn+y9bYphDN4ZpW0E8EwkoxKXUm6d9KItstbfILY35MJ1xHhtGHqSj8jihOU=
  - secure: FRbDzxA4A8zyAHyzZWoMGCyRmsk0n0RYRHlibnbelszRxam17OqWjnVTIzzauQMIyuqQ3oi3k48jUBaYd2RaCXzDABKmlk9QSHD9Q2Sm7YeMQvJHmYLwWxlUsTEA73XSujCH69KH+gSf6b4REWM1IRi+esRgQUxsT2SJ7ItkcUg=
  - secure: B1l0+8+LhvOgQuxfDJXrya5OsFC/uvkvrmbnwj9/VrNcWQlBTSVstPrrdDADR+Bu8YSrHPGVXNC0APcj3jLYKfRDHSwfslvbWhY2CQBjeweo8cJRG/ap69Oc7GFDCaxaSIF2bZ6Qeal4c7Zyeo5z5CZicJD9aiOLsqcRwupAhtg=
  - secure: DGyGiJ+rJrSRVkoidQPqrDnqqC8kgxTOwjJAVUDiTf0ZP971QJTHWi5yM1D/6Y27NxHIcLfae1bTgOFwrb6u/SVhVpY/0gRvDCqhRN87ysSWrN0rKQHB4wXy5tBaS2Thd9tWN61cNQSwUXwbK2aBFt7RuRs0AMr+co2DRAtW4MY=
  - secure: exjLs2/EK4B2H+lSOedvb5bpbQX3O0CVUzm08Yql/1ehU/IyLtkBuoRdtg5p739jDwPPoURuloUNBXyoz6LPlBuniWm2/xU5pnLJqjZvQGQ6Uxkm03PZYWe3jdphT8JKHgLSlc5WQ1WepLTsMvXcEZwIh2vPBTReAe1FbsqzF2I=
matrix:
  allow_failures:
  - env: COREOS_CHANNEL=Stable
  - env: COREOS_CHANNEL=Beta
  - env: COREOS_CHANNEL=Alpha
script: travis_wait 60 ./import_coreos.sh
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_bc0d585c17e3_key -iv $encrypted_bc0d585c17e3_iv
  -in credentials.properties.enc -out credentials.properties -d
